### ISSUE TITLE
Is there a particular reason to use caret (^) for webonyx version?

### ISSUE THREAD

**Issue by therosco** [Ecodev/graphql-upload#2]
I mean https://github.com/Ecodev/graphql-upload/blob/master/composer.json#L27 .

This prevents to use current version of Webonyx, which is 0.11.* .

**Comment by PowerKiKi** [comment]
This is default composer behavior and prevent you from installing versions that might break things, as 0.11 is considered a major, breaking version.

[2.0.1](https://github.com/Ecodev/graphql-upload/releases/tag/2.0.1) was just released to fix that.
