### ISSUE TITLE
Laravel 

### ISSUE THREAD

**Issue by JustinElst** [Ecodev/graphql-upload#3]
I was looking into adding uploads to graphql and i am using Folkloreatelier/laravel-graphql.
But I don't understand how to implement the middleware into Folkloreatelier/laravel-graphql.
As explained in #1 I should use a bridge. But I cant get it working. Could you help me?

**Comment by PowerKiKi** [comment]
I never used Laravel so I won't be able to help you. Maybe you should try on Laravel support channels ?
