### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by herb123456** [Ecodev/graphql-upload#5]
How to use `postman` or `insomnia` to test file upload?

What is the query looks like?

**Comment by herb123456** [comment]
Finally, I use curl in the [spec website](https://github.com/jaydenseric/graphql-multipart-request-spec) to test my graphql endpoint.

**Comment by sirio3mil** [comment]
hi @herb123456 did you finally test it in postman?

**Comment by herb123456** [comment]
@sirio3mil No, I use curl command for testing.

```
curl localhost:3001/graphql \
  -F operations='{ "query": "mutation ($file: Upload!) { singleUpload(file: $file) { id } }", "variables": { "file": null } }' \
  -F map='{ "0": ["variables.file"] }' \
  -F 0=@a.txt
```

**Comment by sirio3mil** [comment]
Just in case this help, it can be done using [this](https://graphql-compose.github.io/docs/guide/file-uploads.html).

Postman now can handle GraphQL call in native way but doesn't support file upload, need to be done using form-data.

**Comment by herb123456** [comment]
The graphql feature inside the postman just in beta, so it can not upload file.

Maybe you can try to convert from that curl command to form data in postman.
