### ISSUE TITLE
Can the dependency webonyx/graphql-php be updated to 14.0.0+？

### ISSUE THREAD

**Issue by moxuandi** [Ecodev/graphql-upload#9]

**Comment by mfn** [comment]
@moxuandi can you make a PR relaxing the composer version constraint? Then we can see if the tests work at least 😄

**Comment by PowerKiKi** [comment]
This is blocked by https://github.com/webonyx/graphql-php/pull/598#issuecomment-666209099

**Comment by xfuturomax** [comment]
Is there any news? Do you need some help in contribution?

**Comment by PowerKiKi** [comment]
Done in b5c5d9b88a6b14a99df4fe1dc302bb8d543c0acd and released as [6.0.0](https://github.com/Ecodev/graphql-upload/releases/tag/6.0.0)
